package com.mavis.mavismcpserver;

import com.mavis.mavismcpserver.mcp.AlistTool.AlistToolService;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.ai.tool.method.MethodToolCallbackProvider;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.mavis.mavismcpserver.dao")
public class MavisMcpServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(MavisMcpServerApplication.class, args);
    }

    @Bean
    MethodToolCallbackProvider toolCallbackProvider(AlistToolService alistToolService) {
        return MethodToolCallbackProvider
                .builder()
                .toolObjects(alistToolService)
                .build();
    }

}
